### ISSUE TITLE
Good Job

### ISSUE THREAD

**Issue by igodogi** [CXH-Research/DocShadow-SD7K#1]
Thanks for the open source contribution, when do you plan to release the code and weights?  In addition, on which GPU was the time spent in Table 2 tested?

**Comment by zinuoli** [comment]
Hi, thank you so much for your attention. We will release our code soon and the dataset has been already released. The GPU is A6000. Feel free to contact us any time.

**Comment by lj163ucas** [comment]
Hello，
The compressed package automatically packaged by OneDrive will miss some samples. Can you please upload the compressed package directly?  
Maybe it can be compressed by volume like your Baidu network disk, but the speed of Baidu network disk is too slow...
