### ISSUE TITLE
Failure to download dataset

### ISSUE THREAD

**Issue by IsHYuhi** [CXH-Research/DocShadow-SD7K#10]
Thanks for publishing this great dataset.

I would like to download the data, but I am having trouble copying it using the Onedrive or Sharepoint functions. Also, I downloaded the files directly, but I can't extract them with 7zip, the files could be corrupted during the download process.

Has anyone been able to solve this problem in a similar situation?

**Comment by xuhangc** [comment]
@zinuoli

**Comment by zinuoli** [comment]
Hi, the OneDrive link is working fine and the zip files are good too. May you check your Internet environment? Many people have asked me the question about dataset and they are able to download files normally.

**Comment by IsHYuhi** [comment]
Thank you for your confirmation.

May I have the embedded link for OneDrive download to download with wget?
Also, do you use 7zip to extract the 7z files?

**Comment by zinuoli** [comment]
Yes I do use 7zip. Did you download all of the zip files from  01 to 04? These files are connected together and cannot be extracted separately.

**Comment by IsHYuhi** [comment]
I was trying to extract files individually. Thank you very much.

**Comment by zinuoli** [comment]
No worries :)
