### ISSUE TITLE
how to remove shading after deshadow?

### ISSUE THREAD

**Issue by weinixuehao** [CXH-Research/DocShadow-SD7K#11]
remove shading for scanning document quality?

**Comment by zinuoli** [comment]
Thank you for your question. Due to the domain gap of different images, there's no perfect shadow removal method, so shading will remain in most of the conditions. Currently we don't provide such pipeline, so you may find your own solution. Sorry about that.

**Comment by xuhangc** [comment]
I am not quite sure what you mean. Maybe you can provide more detailed description or visual samples?
