### ISSUE TITLE
Questions about the config file and the results

### ISSUE THREAD

**Issue by Jerry-woodson** [CXH-Research/DocShadow-SD7K#12]
Dear author, thanks for the great work! I have a question with the config file and the results. Is the training epoch is set with 300, the batch size is set with 4, the datasets SD7K full dataset? If so, is there a demand for GPU? And if possible, could I know more details with the training process? Best regards.

**Comment by zinuoli** [comment]
Hi, thanks for your question. The training epoch is set to 300 and the batch size is normally set to 4 or 8. The params in the config file are not always correct. You should set it by yourself.

**Comment by Jerry-woodson** [comment]
Thanks for the reply! And which epoch is the usually best epoch? I try to reproduce this work these days, but just get 20 in psnr, and could not get more than 28 in psnr. If there is a demand for GPU?

**Comment by Jerry-woodson** [comment]
Could you please give me more details with the training process, like the training log or the tensorboard and so on?

**Comment by zinuoli** [comment]
We use four A6000 GPUs, batch size with 4 and epoch with 300. Normally when the epoch comes to around 280, you get the best performance. Also you can try using our released pretrained models. We re-trained the models previously and even get psnr of 30.

**Comment by zinuoli** [comment]
Could you please provide your configuration you set now? I am happy to help you.

**Comment by Jerry-woodson** [comment]
Great thanks, could we have a discussion through the wechat? I have sent my wechat through the email, hope that we could have a further discussion!

**Comment by Jerry-woodson** [comment]
![image](https://github.com/CXH-Research/DocShadow-SD7K/assets/92074601/bf4ae92b-0f56-48ad-8861-95002de3049e)

**Comment by Jerry-woodson** [comment]
Hi, this is my configuration file, could you please have a look for me?

**Comment by zinuoli** [comment]
Hi, sorry for late reply. I think discussing here would be better cuz this could be a reference for those who have the same question.

**Comment by Jerry-woodson** [comment]
That's fine, thanks

**Comment by zinuoli** [comment]
Seems like your config is good, did you use full dataset for training?

**Comment by zinuoli** [comment]
@xuhangc

**Comment by Jerry-woodson** [comment]
Yeah, I use the full dataset for training.

**Comment by xuhangc** [comment]
I think your config is all good. GPU is only related to the training speed.

**Comment by zinuoli** [comment]
Then I can't think of where the problem is...I think we could help you with a training log, please give us a few time.

**Comment by zinuoli** [comment]
Let's discuss on Wechat and get back to here after we find the problem.

**Comment by Jerry-woodson** [comment]
That's fine, thanks

**Comment by zinuoli** [comment]
Issue closed since the problem has been solved, we've provided log [here](https://wandb.ai/xuhangc/shadow/runs/3n6dlkn5) and details. Feel free to reopen it again.

**Comment by Jerry-woodson** [comment]
The question has been finished, thanks!
