### ISSUE TITLE
[question] about the pretrained model

### ISSUE THREAD

**Issue by cactusgame** [CXH-Research/DocShadow-SD7K#13]
Thanks for sharing your paper and codes. Could you please tell me, with how many image resources and for how many epochs was the pre-trained model provided in this code repository trained?

**Comment by zinuoli** [comment]
Hi, the image resources are different from each dataset, you can refer to section 7 in our paper (supplementary). For the training epochs we set 300 for all experiments, you can refer to [here](https://github.com/CXH-Research/DocShadow-SD7K/blob/5dbdcd9f9a3cf4dcbd9f4de8c32a081fd56d51a1/config.yml#L9).
