### ISSUE TITLE
How much GPU memory needed for training at full size dataset (2462x3699)?

### ISSUE THREAD

**Issue by luser350** [CXH-Research/DocShadow-SD7K#14]
Thanks for sharing your great work. I'm just curious about the GPUs you used to train a full-size dataset.

**Comment by xuhangc** [comment]
If training the model at full-size resolution is not necessary, it's advisable to use a lower resolution to optimize resource usage and training efficiency. However, if training at full-size resolution is essential for your specific use case, you can consider the following approach to mitigate the high VRAM requirement:

Set batch_size=1 and enable half-precision floating-point format (fp16) during training. By utilizing fp16, you can significantly reduce the memory footprint of the model, allowing it to fit within a VRAM budget of less than 20GB.

Keep in mind that setting batch_size=1 may impact the training dynamics and convergence speed compared to using larger batch sizes. Therefore, it's important to monitor the training progress closely and adjust other hyperparameters as needed to ensure satisfactory performance.

If possible, it's still recommended to explore alternative strategies, such as using a lower training resolution or employing model compression techniques, to strike a balance between computational efficiency and model performance.

**Comment by zinuoli** [comment]
Hi, we just trained the model in 512x512 instead of full-resolution. We tested on full-resolution.
