### ISSUE TITLE
How to test single image by using Pre-trained model

### ISSUE THREAD

**Issue by kerberosargos** [CXH-Research/DocShadow-SD7K#18]
Hello firstly thank you for your great work. 

is there any way to test this model with only single image by using your pre-trained model which is "SD7K.pth"

Thank you in advance.

**Comment by xuhangc** [comment]
Hi, I have updated the single.py which can test single image.

**Comment by kerberosargos** [comment]
Firstly thank you for your support. I am trying to test pre-trained checkpoint on CPU. I have changed codes for this. After that when I using "single.py" I am getting as following error

![resim](https://github.com/CXH-Research/DocShadow-SD7K/assets/11364304/0afdc3d0-8f5a-45d6-9b54-e1443dade71b)

is there any advice for achiving this error?

Thank you in advance.

**Comment by kerberosargos** [comment]
Hello again, After changed as following code

`model, testloader = accelerator.prepare(model)`

to this

` model = accelerator.prepare(model)`

I am not getting as last error. Bu now I am getting as following new error like this

![resim](https://github.com/CXH-Research/DocShadow-SD7K/assets/11364304/43544506-deb0-4044-a4ec-d80595633937)

**opt.TESTING.WEIGHT** value is **./checkpoints/SD7K.pth**

**Comment by kerberosargos** [comment]
Hello again. After modified **single.py**  as following codes. It is working

```
import warnings
from accelerate import Accelerator
from torchvision.utils import save_image
import torchvision.transforms.functional as F
from tqdm import tqdm
from PIL import Image
import numpy as np
from config import Config
from models import *
from utils import *
import os
import cv2
import torch

warnings.filterwarnings('ignore')

opt = Config('config.yml')

seed_everything(opt.OPTIM.SEED)

def single_test(path_img):

    img = cv2.imread(path_img)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) # H, W, C

    img_tensor = torch.tensor(img, dtype=torch.float32) # Convert to torch tensor
    img_tensor = img_tensor / 255. # Normalize [0 - 1] range (but depends on the model)
    img_tensor = img_tensor.permute(2, 0, 1) # Reorder to C, H, W (torch requires this format)
    img_tensor = img_tensor.unsqueeze(0) # Becomes this format B, C, H, W

    accelerator = Accelerator()

    # inp = Image.open(path_img).convert('RGB') 
    # inp = np.array(inp)
    # inp = F.to_tensor(img_tensor)

    # Model & Metrics
    model = Model()

    print(opt.TESTING.WEIGHT)

    load_checkpoint(model, opt.TESTING.WEIGHT)

    model = accelerator.prepare(model)

    model.eval()

    if not os.path.exists("result"):
        os.makedirs("result")

    with torch.no_grad(): # Dont run your gradients, speeds up inference
  
        res = model(img_tensor)

        save_image(res, os.path.join(os.getcwd(), "result", os.path.basename(path_img)))

if __name__ == '__main__':
    path_img = './input/515d9bb410b14e5fb13d1e54fa5e9abd-ezsam.png'
    single_test(path_img)
```

Thank you so much your support again.

**Comment by xuhangc** [comment]
Sorry I was busy with other things and didn't notice the GitHub notification.
