### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by lj163ucas** [CXH-Research/DocShadow-SD7K#2]
Hello，
The compressed package automatically packaged by OneDrive will miss some samples. Can you please upload the compressed package directly?
Maybe it can be compressed by volume like your Baidu network disk, but the speed of Baidu network disk is too slow...

**Comment by xuhangc** [comment]
I think you can copy the OneDrive files to your own OneDrive and Syn locally. You may refer to this [link](https://support.microsoft.com/en-us/office/copy-files-from-another-person-s-onedrive-7eb33f7d-6540-488f-afaf-56043828e47b)

**Comment by zinuoli** [comment]
Hi, thanks for your comment. As mentioned above, you may try to copy the files to your own OneDrive. Also, we will upload the compressed files to OneDrive soon if you are not that in a hurry.

**Comment by zinuoli** [comment]
Hi, the compressed files have been uploaded. Now you can download them by clicking the "SD7K (OneDrive)" again.
