### ISSUE TITLE
Question about some details of the paper

### ISSUE THREAD

**Issue by lj163ucas** [CXH-Research/DocShadow-SD7K#3]
![Image_20230831154432](https://github.com/CXH-Research/DocShadow-SD7K/assets/126590140/72883aa0-b406-412b-ba81-c2a0865c3038)
1. Are the test results of the proposed model the same model at three resolutions?  Or separately trained?
2. The paper mentioned the use of synthetic means, and the effect has been greatly improved.  What are the details and will it be implemented in open source?

**Comment by xuhangc** [comment]
The original shadow generation pipeline can be found [here](https://github.com/CXH-Research/Shadow-Generation).

However, our implementation is not as efficient as desired. Therefore, we utilize Albumentations, a more elegant solution.

https://github.com/CXH-Research/DocShadow-SD7K/blob/a0d2eeb0f3dc5f5b6019c52337d2e6ba13b16f34/data/dataset_RGB.py#L39-L41

**Comment by zinuoli** [comment]
Hi, all the results come from the model trained on the original size. Also, we implemented super resolution to those methods that could not generate high-resolution results as the reviewers required.

**Comment by lj163ucas** [comment]
Thank you both for your responses. It's great.

By **original size**, do you mean full resolution, 2462 * 3699?  Or 512 * 512? 
As I read that the resolution set in config.yml is 512, so I would like to double check the size of the training. 

In addition, I would also like to discuss that there are still some shadowy ghosts in the current results. Is there any better way, or should we further improve from what aspects?

**Comment by zinuoli** [comment]
Yes, the **original size** means the 2k resolution 2462 * 3699. The parameters in `config.yml` are just a reference for you. Also, you can refer to the `SESSION` in `config.yml`, it is supposed to be the config of Jung dataset.

In terms of the shadowy ghosts, we are sorry but problems exist in most of the current learning-based methods, we will try to improve it in the future. You may also try to read some papers and get ideas for improving the results. I would say the masks are good tools to guide the network, but our network is **MASK-FREE**.

**Comment by zinuoli** [comment]
Hi, sorry for the wrong reply a few days ago. The model on SD7K was trained on 512*512 and tested on three different resolutions. 
The previous reply was incorrect.

All the selected methods were trained on 512*512 and tested on three distinct resolutions.

**Comment by lj163ucas** [comment]
ok, got it.

**Comment by shallweiwei** [comment]
It looks like the code for Albumentations is pretty simple. Can this achieve the same effect as the original article？ @zinuoli @xuhangc 
The result of my attempt is like this. It looks very strange.

<img width="546" height="729" alt="Image" src="https://github.com/user-attachments/assets/ff2c2b49-6e54-4841-8358-2fb33653bc81" />

**Comment by xuhangc** [comment]
You can also use our [original pipeline](https://github.com/CXH-Research/Shadow-Generation). However, we found that the difference was very marginal. @shallweiwei

**Comment by shallweiwei** [comment]
Thank you very much for your reply. Have you tried to use the above kind of pictures? Will it really help the model? It does seem rather bad. @xuhangc

**Comment by xuhangc** [comment]
Yes, and the results look good. I'd argue that when it comes to shadows, how many and how diverse they are matters far more than how good any single one looks.
@shallweiwei

**Comment by shallweiwei** [comment]
Thank you very much for your reply. I'll try again. @xuhangc
