### ISSUE TITLE
Issue With Multi-GPU Training in DocShadow-SD7K

### ISSUE THREAD

**Issue by GPTOT** [CXH-Research/DocShadow-SD7K#4]
Hi, I'm utilizing your project for document shadow removal and I've been impressed by the results with the pre-trained model. Now, I'm trying to train a model on my own dataset. My system has multiple GPUs and I would like to leverage them for the training process. However, when I execute the following command as per your instructions:

```
accelerate config
accelerate launch train.py
```

I encounter an error message related to the `accelerate launch train.py` part. I'm not exactly sure what's causing this problem. Please let me know if you need additional information.

**To Reproduce**
1. git clone https://github.com/CXH-Research/DocShadow-SD7K.git
2. cd DocShadow-SD7K
3. pip install -r requirements.txt
4. accelerate config
5. accelerate launch train.py

**Expected behavior**
I expected the code to start training using all available GPUs on my machine.

**Additional context**
I'm able to run the training script with a single GPU using `python train.py` without any issues. However, I would like to speed up the training process by using multiple GPUs.

Thank you very much for any assistance you can provide.

**Comment by zinuoli** [comment]
Good day mate. To enable multiple GPUs training, you may first need to know how the [Accelerate](https://github.com/huggingface/accelerate) works by following the instruction of it.

To be specific, you would first specify the machines, GPU ids, etc. as required by `accelerate config`. Once you have specified all the parameters, you can enable multiple GPUs training simply by running `accelerate launch train.py`.

**Comment by zinuoli** [comment]
![image](https://github.com/CXH-Research/DocShadow-SD7K/assets/94612909/4584739e-53e6-452b-b8e8-8a1d796e5bb1)
This would be a reference for you, feel free to raise any other issues and we will get to you as soon as possible.
