### ISSUE TITLE
Convert to ComeML

### ISSUE THREAD

**Issue by heorhiikalaichev** [CXH-Research/DocShadow-SD7K#6]
Hi!

Thank you for your job!
Please, tell me. Is it possible to convert your model to coreml?

Thank you in advance!

**Comment by xuhangc** [comment]
Converting a PyTorch checkpoint directly to CoreML is not supported. However, there is an available ONNX solution https://github.com/fabio-sim/DocShadow-ONNX-TensorRT, which enables the conversion of ONNX models to CoreML.
