### ISSUE TITLE
Question about the illumination of SD7K

### ISSUE THREAD

**Issue by HSDai** [CXH-Research/DocShadow-SD7K#7]
Thank you for your contribution!

I notice that the ground truth of one document has the same lighting, while corresponding shadowed documents are illuminated with lighting of different color temperatures. For example, IMG_6484.png to IMG_6499.png, 
![IMG_a](https://github.com/CXH-Research/DocShadow-SD7K/assets/99655603/2e02e788-0521-42b1-b487-3a89859cd847)
![IMG_b](https://github.com/CXH-Research/DocShadow-SD7K/assets/99655603/16ae66a4-b550-483b-bb19-4339194f3149)

Additionally, the light of the ground truth does not seem to be sunlight.

So I have questions: Does the shadow removal task in this dataset ensure consistent lighting before and after removing shadows? If not, why aren't the ground truth images illuminated with sunlight?

**Comment by xuhangc** [comment]
Thank you for your inquiry.

Our study utilizes three sets of lighting conditions: indoor cool light, indoor warm light, and outdoor sunlight. For indoor lighting, we can maintain consistent lighting as the light source remains invariant. However, for outdoor sunlight, perfect alignment is unattainable, which is the same as other shadow datasets.

If your question pertains to why we employ varying types of lighting, it is based on our assumption that most document scanning occurs in indoor office environments. Hence, outdoor scenarios are not typically the primary focus of our study.
