### ISSUE TITLE
Detail about the DFE

### ISSUE THREAD

**Issue by igodogi** [CXH-Research/DocShadow-SD7K#9]
Why you set DFE default config as this? Why decoders as the same? 
https://github.com/CXH-Research/DocShadow-SD7K/blob/78dd930b21e02ea527ac70651a10ff0055e82795/models/backbone.py#L116C60-L116C60

Is there a better way to expand the depth of DFE?

**Comment by zinuoli** [comment]
Hi, good day. We tried the number of blocks opposite to the encoder, which is 8, 4, 2, 2. At the same time, we also attempted other combinations. However, these combinations did not enhance the performance (only very slight improvement, or even negative improvement), but the amount of parameters increased significantly. To maintain the ability of inference under high resolution and faster speed, we chose the current config. 

Moreover, you may try increasing the number of decoders by yourself, but at present, the number of decoders is the optimal choice. You can consider DFE simply as a U-Net.
